# Generated by Django 5.0.6 on 2024-05-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('facebook_token', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('apple_id', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=15)),
                ('user_login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.userlogin')),
            ],
        ),
    ]
