# Generated by Django 5.0.6 on 2024-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='apple_id',
            field=models.CharField(blank=True, default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='facebook_token',
            field=models.CharField(blank=True, default=1111111, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='phone_number',
            field=models.CharField(blank=True, default='1111', max_length=15),
            preserve_default=False,
        ),
    ]
