# Generated by Django 5.0.6 on 2024-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_categories_remove_userhobby_hobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
