# Generated by Django 5.0.6 on 2024-06-14 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_mode_user_show_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been', models.JSONField(default=list)),
                ('want_to_go', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
