# Generated by Django 5.0.6 on 2024-06-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_countries',
            new_name='UserCountries',
        ),
    ]
