# Generated by Django 5.0.6 on 2024-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_countries_usercountries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercountries',
            name='has_been',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='usercountries',
            name='want_to_go',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
