# Generated by Django 5.0.6 on 2024-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usercountries_has_been_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_created_profile',
            field=models.BooleanField(default=False),
        ),
    ]
